# Pre-commit configuration for Rust project
repos:
  # Rust-specific hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      # Format code with cargo fmt
      - id: fmt
        name: cargo fmt
        description: Format Rust code with cargo fmt
        entry: cargo fmt
        language: system
        files: \.rs$
        args: ['--all', '--']

      # Run cargo clippy for linting
      - id: clippy
        name: cargo clippy
        description: Lint Rust code with cargo clippy
        entry: cargo clippy
        language: system
        files: \.rs$
        args: ['--all-targets', '--all-features', '--', '-D', 'warnings']

      # Check that code compiles
      - id: cargo-check
        name: cargo check
        description: Check that Rust code compiles
        entry: cargo check
        language: system
        files: \.rs$
        args: ['--all-targets', '--all-features']

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace

      # Ensure files end with newline
      - id: end-of-file-fixer

      # Check for merge conflicts
      - id: check-merge-conflict

      # Check YAML syntax
      - id: check-yaml

      # Check TOML syntax
      - id: check-toml

      # Prevent large files from being committed
      - id: check-added-large-files
        args: ['--maxkb=1000']
